---
platform: linux
image_resource:
   type: docker-image
   source: {repository: dingotiles/dingo-backup-storage-pivotaltile-pipeline}

inputs:
- name: tile
- name: tile-version
- name: dingo-backup-storage-boshrelease
  path: dingo-backup-storage
- name: pivnet-stemcell

outputs:
- name: product

run:
  path: tile/ci/tasks/generate-product.sh
